### PR TITLE
Bugfix/wice gpu

### PR DESCRIPTION
**Pull request by moravveji**
A user reported a typographic mistake in the wICE quickstart, and I have just fixed that (GPU example).

### CODE REVIEW

**Comment by moravveji** [comment]
@mselwa : I am merging my branch to the `development` branch, but I see the whole long list of older commits. This is certainly not the idea.
Isn't it the correct workflow to merge to development?
My branch is checkedout from the `master`.

**Comment by mselwa** [comment]
looks ok

**Review by mselwa — COMMENTED** [review]
ok

**Comment by moravveji** [comment]
because of a divergence of the master branch vs the development branch, i prefer to close this PR until the two are brought in agreement again.

**Pull request closed without merging**
