### PR TITLE
Update vsc_tutorials.rst

### PR DESCRIPTION
**Pull request by mselwa**
remove pdfs for KUL

### CODE REVIEW

**Review by backelj — APPROVED** [review]

**Review by moravveji — APPROVED** [review]
There are no internal references to these static links. So, this PR looks good to me.

**Review by jooghe — APPROVED** [review]
OK For me. Thanks;

**Comment by smoors** [comment]
@mselwa while you're at it, can you please also remove the PDFs for VUB?
thanks!

**Comment by stevenvdb** [comment]
For KU Leuven/UHasselt, I would consider adding the link to our HPC-Intro course (https://hpcleuven.github.io/HPC-intro/).

**Comment by moravveji** [comment]
> For KU Leuven/UHasselt, I would consider adding the link to our HPC-Intro course (https://hpcleuven.github.io/HPC-intro/).

This is in general a good idea, but at the moment, we are quite modifying the format of our presentation. Furthermore, the video recordings are obsolete, so, that can be quite confusing to the users.
Perhaps when the training material are updated, we can consider adding the link to it here.

**Comment by lexming** [comment]
@stdweird @smoors @stevenvdb I added your suggestions to the document and reformatted it a bit, please check and let me know if it can be merged

**Comment by stdweird** [comment]
@lexming fine by me. thanks for doing this

**Review by boegel — APPROVED** [review]

**Pull request merged**
