### PR TITLE
add html_title

### PR DESCRIPTION
**Pull request by smoors**
this reduces the lengthy text on the navigation bar from 'VSC documentation 1.0 documentation' to simply 'VSC documentation'

### CODE REVIEW

**Comment by smoors** [comment]
@gjbex I did this to remove the double 'documentation', but feel free to close it if you don't want this.

**Comment by smoors** [comment]
@gjbex ping?

**Review by gjbex — APPROVED** [review]
Sorry for the late reply (I get too many GitHub messages, mostly not for me anyway).

Good idea.

**Comment by smoors** [comment]
Don't worry, I have the same problem :smile:

**Pull request merged**
