### PR TITLE
add note to conda usage for installing additional packages

### PR DESCRIPTION
**Pull request by smoors**
add note to usage of `conda` for installing additional R and Python packages

### CODE REVIEW

**Review by stevenvdb — APPROVED** [review]

**Review by boegel — APPROVED** [review]

**Comment by smoors** [comment]
@sbecuwe are you ok with adding this note?

**Comment by sbecuwe** [comment]
Yes.

**Comment by boegel** [comment]
Seems like we have approval from UGent, VUB, KUL and UA on this, so I'll go ahead and merge. Thanks @smoors!

**Comment by boegel** [comment]
Ah, except... I don't have merge rights.

**Comment by lexming** [comment]
:muscle:

**Pull request merged**
