### PR TITLE
Superdome documentation

### PR DESCRIPTION
**Pull request by gjbex**
Try to reduce confusion in Superdome documentation.

### CODE REVIEW

**Comment by moravveji** [comment]
I see that this branch is merged now. All seems ok, but there is this whole subsection about the login (load-balancer, choice of NX, visualization node etc) which to my idea, does not belong to her. A user who wants to find more info about Genius logins should not jump to the superdome page to find his desired info.
So, I just think it would be better to place a link to the relevant login pages, instead.

**Comment by moravveji** [comment]
Furthermore, it is perhaps also worthwhile to mention the MTM compiler suit for users who would like to compile their codes on superdome.

**Comment by gjbex** [comment]
The information on the login nodes was there in the past as well.  It is now consistent with the other information on login to genius.

The point is that this is in fact a quickstart, not necessarily aimed at genius users, e.g., users from other universities/externals.  Now it reads as a single page, without having to move to other pages and back.

I don't know about the compiler you mention, so please enlighten me.

**Comment by moravveji** [comment]
Sure ... 
The correct name of the tool is **MPT** and not MTM, my bad.
On the Superdome quick start guide (.docx) file on sharepoint (gedeelde documenten -> cursus) you can find quite detailed info about the specialized MPT compiler for intel and foss. I just thought that this could also be useful for some users.

**Pull request merged**
